# Generated by Django 4.1.5 on 2023-01-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="category"),
            preserve_default=False,
        ),
    ]
